# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Campos Lab
tagline:          'Laboratório do Alex'
description:      'Bem vindo ao meu laboratório de programação! Fique a vontade para perguntar qualquer coisa.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Alex Campos'
  url:            https://twitter.com/

paginate:         5

plugins:
  - jekyll-seo-tag

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/camposlab
